# Generated by Django 3.1.6 on 2021-02-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('subtitle', models.CharField(default='', max_length=500)),
                ('details', models.TextField(default='')),
                ('feature_image', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bikedata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BikeUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=12, null=True)),
                ('password', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'bikeuser',
                'managed': True,
            },
        ),
    ]
